export const randomFacts = [
    "I love rice chips",
    "My phone is alive for 7 years already. It's Sony Xperia XZ Premium",
    "I hate fish and ketchup",
    "I only have 1 NSFW art in my collection (it's ok)",
    `Today it's ${(new Date).getDate()}.${(new Date).getMonth() + 1}.${(new Date).getFullYear()}`,
    "This and drawings page took me 16+ hours of work",
    "I took that discord name just because I thought it'll be exclusive in future",
    "For now I'm 18",
    "I've never had actual friends IRL",
    "I'm having fun time writing this",
    "I hope you're not stalking this page",
    "I learned English thanks to Александр Бебрис. Maybe I'll send him some money for this someday. It really means a lot to me everyday",
    "My mom really wants me to eat a lot",
    "I've never played Dota 2",
    "My mouse works on scotch. It has around of 8 years",
    "Before tasting donuts I thought they'll be the same as normal buns, just in other shape. I was wrong",
    "You don't deserve a fact today.",
    "I work on a factory. For now my work shift is 8 hours",
    "I use earphones when I'm on the night shift",
    "I've never smoked and drunk, not going to do this anytime soon",
    "My old neighbour was walking around the house with gasoline canister and pouring water around his dormitory. Perhaps he was taken to a mental hospital",
    "I have 18 creator points in geometry dash. Not the thing I have to be proud of..",
    "I use ChatGPT everyday to fix a lot of code problems. Nowadays it feels like an indispensable tool, if used wisely",
    "All photos size in drawings tab is 12 megabytes",
    "One person actually managed to interest me in webdev and programming more deeply than before",
    "I don't watch tiktok",
    "I bite my nails :(. I'm trying to get rid of this but not succeeding for years..",
    "Imbecille sounds cute",
    "You're not a girl",
    "I broke my own phone when I was a child because I was very angry",
    '"Майни" is the channel which I watch for the longest time for now. Probably for like 5 years or so',
    "Don't bully my English grammar please. Yeah I know it's bad but what can I do?",
    "Proof that internet friends are not actual friends: My friend that I knew for 5 years just deleted me for no reason. I can surely say he wasn't hacked or something else, just his own desire.",
    "I loved Open Hexagon before, tried to remake it in C++ SFML library, Godot and sucked twice. Also I remade it in gd three times. I also have 973 hours in it.",
    "My laptop price is 18999 CZK",
    "Before 18 I used to brush teeth once a day. Now I do it twice a day and trying to save my teeth for future",
    "Why did I styled this site like this? Why not. In my opinion looks quite nice.",
    "Acabus",
    "I used to wash once a week earlier, later I used to wash 2 times a week and now I wash every day except of Saturday.",
    "My favourite game of all time ever: Angry Birds Epic. Sadly after some time it died and there're no as amazing analogues as this game",
    "I don't play games for now. My latest played games are: Flipwitch, Euphoria, LonaRPG",
    "My favourite anime: Made in Abyss. I also watched interspecies reviewers, Oniichan wa Oshimai and school days",
    "Headphones are always over earphones to me",
    "I hate myself from 13 years",
    "I hate talking about same stuff every day. I'm surprised that some people actually enjoy repeating same subjects every time",
    'I rarely visit a location called "Outside"',
    "I played on local agario server with node.js when I was 10",
    "I found all 3 doorknobs with video tutorial in Paper Lily Prologue just to find some library with content I didn't get at all",
    "My laptop has rgb keyboard, i'm elite",
    "During 8 months I spent in czech I'm not sure I've even learned how to properly spell \"hello\". Some people say \"aoj\" and some people say \"chao\"",
    "It took me a while to get used how PM and AM time works",
    "Voices Of The Void is also a cool game if you have a lot of free time and don't hurry with getting scared, I enjoyed this experience",
    "I like counting calories for no reason",
    "Some people wished me death for making geometry dash levels",
    "My hair length is 1.5-2.5cm for now, I hate my hair",
    "This is my best site I made for now",
    "I was making packs for Open Hexagon. Prism took me 9 months to make. My worst time devote ever probably",
    "Reworking long code which is already works is so scary",
    "On the next day you're going to the beginning of random facts array"
]